version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'teest'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
